version: "3"

services:
  driver-aws:
    build: .

    expose:
      - "8080"

    ports:
      - "8080:8080"

    depends_on:
      - database

    environment:
      DATABASE_HOST: database
      DATABASE_NAME: driver_metadata
      DATABASE_USER: driver_robot
      DATABASE_PASSWORD: "dr1v3r"
      USE_FAKE_AWS_CLIENT: "TRUE"


  database:
    image: postgres:11

    volumes:
      # Volume for startup scripts. Note this will only run if there is nothing in /var/lib/postgresql/data
      - ./test/db/init-scripts:/docker-entrypoint-initdb.d

      # Volume for persistance between runs. Uncomment if you wish to retain data.
      # - ./test/db/volume:/var/lib/postgresql/data

    expose:
      - "5432"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: pgsqlDev01
