name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'

    - name: Run Go Tests
      run: |
        go get github.com/golang/mock/mockgen
        go generate ./...
        go test ./... -cover -race

    - name: Run integration tests
      run: |
        docker-compose build
        docker-compose up --detach
        cd test/integration
        npm install
        npm run test && docker-compose down

    - name: Build and Push to Humanitec
      uses: humanitec/build-push-to-humanitec@v1
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
        organization: polarsquad
        humanitec-registry: registry.humanitec.io
        humanitec-api: api.humanitec.io
